### ISSUE TITLE
Fix for GetRasplex.bin under Fedora 20

### ISSUE THREAD

**Issue by flashbackpa** [RasPlex/rasplex-installer#19]
Hi, just to tell you that i had to create a symbolic link to libudev.so.0 using the libudev from google chrome....
Than the installer started correctly.

**Comment by Risca** [comment]
This is most probably related to missing 32-bit libraries on 64-bit systems. Hopefully we will get a native 64-bit installer for Linux soon.

**Comment by Risca** [comment]
Solved by 64-bit linux release in [version 1.0.1](https://github.com/RasPlex/rasplex-installer/tree/1.0.1)
