### ISSUE TITLE
Crash on trailers

### ISSUE THREAD

**Issue by Baswazz** [RasPlex/rasplex-installer#20]
I have enabled to play 2 trailers before the movie starts.
When i hit the next key when a trailer is playing from the software navigation bar plex hangs. I need to restart the Pi.

**Comment by Risca** [comment]
Please read through [How to report a bug](https://github.com/RasPlex/RasPlex/wiki/How-to-report-a-bug) and report this bug on https://github.com/RasPlex/RasPlex/issues
