### ISSUE TITLE
Suspicious.Cloud.7.EP detected by Norton

### ISSUE THREAD

**Issue by GreenRobotics** [RasPlex/rasplex-installer#21]
Norton 360 deletes the file based upon the above classification.

**Comment by dalehamel** [comment]
This is Norton misclassifying the file.

If you don't trust it, you can look at the source code to see what it's
doing. All tr build instructions are available and it should compile to the
same checksum.

Generally speaking, it's terrible from a security perspective to run a file
you downloaded from the Internet as administrator, but this is necessary to
be able to flash the sd card.

If you can't whitelist the file in Norton, try win32diskimager instead.
