### ISSUE TITLE
RaspberryPi 2 Install hangs at resizing /storage

### ISSUE THREAD

**Issue by cghercoias** [RasPlex/rasplex-installer#22]
The install on RaspberryPi 2 with 16GB TF card stops/hangs at:

+++++++++++++
resizing /storage...
this might take a while, please do not reboot or turn off your computer
... parted -s -m /dev/mmcblk0 rm 2
... parted -s -m /dev/mmcblk0 unit b mkpart primary 270532608B 100%
... e2fsck -f -p /dev/mmcblk0p2
... resize2fs /dev/mmcblk0p2

...done. rebooting in 15s
/usr/lib/openelec/fs-resize: line 61: reboot :Input/Output error
+++++++++++++

I have waited more than 30 minutes, no change.
Have checked the power supply, it is 5V and it does provide 2A.
Not sure where/what to do further.
Many thanks.

**Comment by Risca** [comment]
Have you tried using a different SD card? Different power supply (some PSU claim to provide enough power, but doesn't live up to their claim)? Different SD card reader/writer?
I don't believe this issue has anything to do with the installer.

**Comment by cghercoias** [comment]
Changed the SD card with a Sandisk 32GB, 48MB/s and all is good. Rasplex now installs fine.
Thank you.
