### ISSUE TITLE
Drop down selections revert to default when 'Update links' is clicked

### ISSUE THREAD

**Issue by liddellj** [RasPlex/rasplex-installer#23]
First of all - thanks very much for your work on RasPlex - really neat product, much appreciated.

Steps to reproduce:
* Launch installer.
* Select *Raspberry Pi2* for step 1
* Select *0.5.1* for step 2
* Click *Update links*

Expected result:
* Links are updated, but selections remain the same.

Actual result:
* Step 1 selection reverts to *Raspberry Pi* (default value)
* Step 2 reverts to *0.6.0* (default value)

This caught me out as I ended up writing an image for Raspberry Pi 1, when I needed an image for Raspberry Pi2.

I'm running the installer on Windows 7 64 bit.

**Comment by dalehamel** [comment]
Thats' a bug alright.

**Comment by Risca** [comment]
I'll see if I can fix it later this week. Stay tuned!

**Comment by dalehamel** [comment]
Thanks Patrik!
