### ISSUE TITLE
not providing imag file during download

### ISSUE THREAD

**Issue by FLIPDAVE** [RasPlex/rasplex-installer#24]
When I try and download Windows version 6.0, no image file provided in the download; only the executable

**Comment by Risca** [comment]
I'm not sure what you mean. Could you elaborate?

**Comment by FLIPDAVE** [comment]
It's actually quite simple; when selecting Windows for downloading the Plex 6.0 files, only the .exe file is downloaded, not the .img.gz file. The image file does not get automatically downloaded, or end up in the downloading folder on my PC.

Hopefully, that clarifies the situation.

Thanks

David Flippo

**Comment by dalehamel** [comment]
You run the executable to get the image. It's a downloader that helps you
flash the image.
