### ISSUE TITLE
No content over WiFi

### ISSUE THREAD

**Issue by Podiumready** [RasPlex/rasplex-installer#25]
Hey guys, I hope I'm missing something obvious b/c this has me batty.
Hardware:
rPi 1 512 version (blue audio port)
sandisk sdhc C10 16GB
WiFi: Edimax EW-7811Un
netgear n300 (WNR2000)
desktop with plex server

Issue: Everything seems to work fine with network cable. When on wifi, content(movies & channels) isn't found.

From writing to the SD card using rasplex and version 0.6.0 here's what happens:
-The initial setup shows up however when it reaches the wifi selection nothing shows up (I've tried 0.5.1 and wifi networks show up there) come to find after setup that wifi is disabled by default (no network cable is plugged in either at this point) get to main screen shows up with all 'search' options. arrow back to system properties enable wifi it connects, I go to sign in, I get a code, pull it up on server computer enter it and I get a green check on rasplex. then I get the 'watch later' option paired with each 'search' but no movies/channels/content that I have on my plex server (only put on firefly and a couple channels TED, youtube, and soundcloud so it's pretty bare)

I hope that's enough info to get started, let me know what I can try/check/ or provide more info on. Thanks in advance to those who help

**Comment by Risca** [comment]
I don't think this is related to the rasplex-installer. Please post this issue [here](https://github.com/RasPlex/RasPlex/issues) instead.

It sounds to me like a hardware issue. Try using a more powerful power plug or an external, powered USB hub for the WIFI dongle.
