### ISSUE TITLE
Installed version on Windows 7 doesn't work

### ISSUE THREAD

**Issue by 19Gerhard85** [RasPlex/rasplex-installer#26]
I installed RasPlex 0.7.0 for my RPi 2. On boot I only see a big rainbow square.

Installing on Mac with the same SD card works.

**Comment by Risca** [comment]
Hi 19Gerhard85,
Could you help me debug this a little by answering some questions:
What version of Windows 7 (32 or 64 bit)?
Did you use the latest installers (released a few weeks ago)?
Are you 100% sure that your SD card showed up in the installer and was selected?
Did you change between selected install devices before writing to the SD card?

// Risca

**Comment by 19Gerhard85** [comment]
@Risca 
System: Windows 7 Ultimate x64 
Installer: Latest from GitHub

The "history" of the SD card is:
- Installed RasPlex some months ago
- Upgraded the 0.7.0 via RasPlex --> no audio on playback
- Decided to fresh install it, so I moved the SD card into the PC.
- Formatted with the SD card formatter tool (https://www.sdcard.org/downloads/formatter_4/) because the SD card was displayed with ~ 240 MB total size.
- After formatting the size was correct (16 GB)
- Installed with RasPlex Install
- Big rainbow square on boot

Greets

**Comment by Risca** [comment]
Solved by release [1.0.1](https://github.com/RasPlex/rasplex-installer/tree/1.0.1)
