### ISSUE TITLE
Color square on PI 2 after install Plex 6&7 through "Get Rasplex" application on Mac & Win

### ISSUE THREAD

**Issue by Aliendm** [RasPlex/rasplex-installer#27]
Hello.
I have a strange problem after installing rasplex 6 or 7 through a Get Rasplex application on my PI 2.
After i insert micro sd card and power on i see color square on my TV.
First of all i think that something wrong with sd card and i try another one but have the same problem.
Second time i think something wrong with installer and try it in windows, but nothing else.
Then i change power adapter with cord to 5V and 2 A,but the same situation(normally i use 5v 1.5A)
If i use Kodi or other distro from raspbery.com all works good.
But I need Plex, because my NAS have plex server and i need a client on my pi 2.
Thanks.

**Comment by dalehamel** [comment]
The color indicates power supply issues. It might be the default overclocking settings we provide are the problem for you. Try a power suppely that does 5V at 2A.

**Comment by Aliendm** [comment]
Hello , I try to use power adapter with 5V and 2A, but it doesn't change situation.

**Comment by Aliendm** [comment]
Update.The problem is in the Get Rasplex Application
When you choose RPI 2, program doesn't swith and download image for RPI 1

**Comment by Risca** [comment]
I thought we fixed that issue... I might have some time this weekend or next week to look at it

**Comment by Aliendm** [comment]
Thanks

**Comment by Risca** [comment]
@Kwiboo uploaded some fixes for this a few days ago. I will try to get new binaries out during next week along with some other few tweaks :)

**Comment by Aliendm** [comment]
Thanks a lot!
