### ISSUE TITLE
Installer doesn't work on Linuxmint Debian 64bit

### ISSUE THREAD

**Issue by franky384** [RasPlex/rasplex-installer#28]
i get this error when i try to run GetRaslex.bin:
./GetRasplex.bin: error while loading shared libraries: libblkid.so.1: wrong ELF class: ELFCLASS64

**Comment by Risca** [comment]
It's because it's a 32-bit binary, that links to 32-bit libraries. We're working on getting a 64-bit binary released so we won't have these problems anymore (see #19).
In the meantime, a workaround is to install the missing 32-bit libraries:
```
sudo apt-get install libblkid:i386
```

**Comment by franky384** [comment]
Ok, no prob, i installed manual.
