### ISSUE TITLE
Attempting to write to Read-Only SD with Windows Installer gives Chinese error.

### ISSUE THREAD

**Issue by blakev** [RasPlex/rasplex-installer#30]
I was trying to write Rasplex via the Official Rasplex Installer and it was giving me a cryptic error that contained Chinese.

It turns how the "write protection" was flipped the SD card.

I would assume users could see that and panic ~ should be an easy fix.

![image](https://cloud.githubusercontent.com/assets/4885156/9917106/10b2ceee-5c7d-11e5-90eb-577bf7580c8c.png)

**Comment by dalehamel** [comment]
Most likely the error message is not being put into unicode and it's rendering the raw byte sequence as ascii which turns out to be chinese characters?

Weird theory
