### ISSUE TITLE
OSX installer fails to get devices from updater.raspblex.com

### ISSUE THREAD

**Issue by marcokeur** [RasPlex/rasplex-installer#32]
Just downloaded the latest version. It tells me in the console;
`Refreshing removable devices list
Getting  QUrl( "http://updater.rasplex.com/devices" ) 
QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
QSslSocket: cannot resolve SSL_select_next_proto
QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
Something went wrong with the get request: "Error downloading http://updater.rasplex.com/devices - server replied: Not Found"
`

Trying to load the url in my browser shows: 
`Cannot GET /devices`

**Comment by Risca** [comment]
This seems to be resolved for some time now
