### ISSUE TITLE
Bad URL in installer.cpp

### ISSUE THREAD

**Issue by malexandre** [RasPlex/rasplex-installer#33]
My installer is stuck on "Getting supported RasPlex devices".

I don't know if the problem is from this installer or the server configuration, but the installer try to get the list of version & devices from [http://updater.rasplex.com/devices](http://updater.rasplex.com/devices). But calling this URL from my browser gets me a 404.

**Comment by dalehamel** [comment]
@malexandre hi, this was a bug in the update server and should now be resolved. Please retry your download and sorry for the inconvenience
