### ISSUE TITLE
Can access the USB HDD device but super slow. pls help. Thanks.

### ISSUE THREAD

**Issue by suptronics** [RasPlex/rasplex-installer#46]
Hello Friends,

Apprecaite if you can help to reslove below issue. Connected an USB HDD to Raspberry Pi but it was running super slow. have verified that the USB storage device can work fine with the PC so I was thinking there might be an issue with the system or my wrong operation. 

Please see below details. thanks for your help in advance.
 
When I try to access the disk via the Raspberry Pi it is SUPER SLOW. I have tried this with a fresh install a few times, here is my latest log (with my comments in YELLOW):
 
Last login: Thu Apr 26 11:22:53 2018 from 192.168.1.187
pi@plexpi:~ $ sudo lsblk -o UUID,NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL,MODEL 
UUID                                 NAME        FSTYPE   SIZE MOUNTPOINT LABEL                                     MODEL
                                     sda                931.5G                                                      Generic
                                     ├─sda1               128M                                                     
8026891D268914F6                     └─sda2      ntfs   931.4G            Media                                    
                                     mmcblk0             29.7G                                                     
A365-6756                            ├─mmcblk0p1 vfat    43.1M /boot      boot                                     
90a83158-560d-48ee-9de9-40c51d93c287 └─mmcblk0p2 ext4    29.7G /          rootfs
 
THIS WAS SUPER FAST AND WORKING AS INTENDED
 
                                   
pi@plexpi:~ $ sudo blkid 
/dev/mmcblk0p1: LABEL="boot" UUID="A365-6756" TYPE="vfat" PARTUUID="97dae6a0-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="90a83158-560d-48ee-9de9-40c51d93c287" TYPE="ext4" PARTUUID="97dae6a0-02"
/dev/sda2: LABEL="Media" UUID="8026891D268914F6" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="a282e94d-e317-4eb6-a283-1a683c3d5e78"
/dev/mmcblk0: PTUUID="97dae6a0" PTTYPE="dos"
/dev/sda1: PARTLABEL="Microsoft reserved partition" PARTUUID="5357fd1f-7216-4150-866f-fdc925fa0a37"
 
SUDO BLKID EVENTUALLY FINISHED, BUT TOOK 30 MINUTES BEFORE THE RESULT CAME BACK, IF I TRY IT WITHOUT THE USB IT RESPONDS IMMEDIATELY
 
pi@plexpi:~ $ ls /mnt/
mediahdd
pi@plexpi:~ $ sudo mount /dev/sda2 /mnt/mediahdd
 
THIS IS STILL RUNNING AND HAS NOT YET FINISHED AFTER 30+ MINUTES
 
I am not sure what the problem is, I have been using this Raspberry Pi as a Plex media server, with a network disk and it has been running fine.
 
I have tried a fresh install twice, and am still having issues.
 
The disk works fine if I try it on another computer.

**Comment by Risca** [comment]
RasPlex is for running Plex home theater (the client) on a raspberry pi, not for running the server. This repository in particular is for the RasPlex installer. I think your best option is to ask for help in either the raspberry pi or plex forums.
Closing issue as out of scope. Sorry.
