### ISSUE TITLE
Auto hide play controls

### ISSUE THREAD

**Issue by Zamana** [RasPlex/rasplex-installer#47]
OpenPHT is THE BEST plex player.  Period.

But it needs a feature (sorry if it has already; I could no find it) that is: it needs to hide the play controls automatically.

As it is today, you need to press the equivalent "esc" in your remote control in order to hide the play controls...

Thanks.
Regards.

**Comment by Risca** [comment]
This repository is for the installer of RasPlex, not the actual RasPlex/OpenPHT. Please report your issue here: https://github.com/RasPlex/OpenPHT/issues
